CREATE TABLE skype_messages (
	'id' BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	'author' VARCHAR(255) DEFAULT NULL,
	'text' VARCHAR(255) DEFAULT NULL,
	'time' BIGINT DEFAULT NULL,
	'convoName' VARCHAR(255) DEFAULT NULL
);

CREATE TABLE node_errors ( 
	'id' BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	'errorMessage' VARCHAR(255) NOT NULL, 
	'stackTrace' VARCHAR(255) NOT NULL, 
	'time' BIGINT NOT NULL 
);